import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import logo from "../assets/logo.png";

/**
 * Generates a PDF by creating a temporary, hidden HTML element from a template,
 * rendering it with html2canvas (which handles Arabic/RTL perfectly), 
 * and saving it via jsPDF.
 */
export const generateArabicPdf = async (templateHtml, fileName = "document.pdf") => {
    // Create a temporary container
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = '800px';
    container.style.padding = '40px';
    container.style.backgroundColor = 'white';
    // Use Poppins for English and Cairo for Arabic
    container.style.fontFamily = "'Cairo', 'Poppins', sans-serif";
    container.innerHTML = templateHtml;

    document.body.appendChild(container);

    try {
        const canvas = await html2canvas(container, {
            scale: 2,
            useCORS: true,
            logging: false,
            allowTaint: false, // Changed to false for better security/reliability with CORS images
            backgroundColor: "#ffffff",
            windowWidth: 800
        });

        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

        pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
        pdf.save(fileName);
    } catch (error) {
        console.error("PDF Generation failed", error);
        throw error; // Re-throw so the caller knows it failed if they care
    } finally {
        document.body.removeChild(container);
    }
};

/**
 * Helper to build common sections for the PDF template to keep consistency
 */
export const buildPdfTemplate = (title, sections, lang = 'en', centerName = "Iman Islamic Center") => {
    const isRtl = lang === 'ar';
    const direction = isRtl ? 'rtl' : 'ltr';
    const textAlign = isRtl ? 'right' : 'left';

    return `
        <div style="direction: ${direction}; text-align: ${textAlign}; color: #333; font-family: ${isRtl ? "'Cairo', sans-serif" : "'Poppins', sans-serif"}; padding: 20px;">
            <div style="display: flex; align-items: center; border-bottom: 2px solid #27569b; padding-bottom: 20px; margin-bottom: 30px; flex-direction: ${isRtl ? 'row-reverse' : 'row'};">
                <img src="${logo}" style="width: 80px; height: 80px; margin-${isRtl ? 'left' : 'right'}: 20px;" />
                <div style="flex: 1; text-align: center;">
                    <h1 style="color: #27569b; margin: 0; font-size: 28px;">${centerName}</h1>
                    <h2 style="color: #666; margin: 5px 0 0 0; font-size: 18px;">${title}</h2>
                </div>
            </div>
            
            ${sections.map(section => `
                <div style="margin-bottom: 25px;">
                    <div style="background-color: #27569b; color: white; padding: 5px 15px; font-weight: bold; margin-bottom: 15px; border-radius: 4px;">
                        ${section.title}
                    </div>
                    <div style="padding: 0 10px;">
                        ${section.fields.map(field => `
                            <div style="margin-bottom: 10px; display: flex; justify-content: space-between; border-bottom: 1px dotted #ccc; padding-bottom: 4px; flex-direction: ${isRtl ? 'row-reverse' : 'row'};">
                                <span style="font-weight: 700;">${field.label}:</span>
                                <span>${field.value || '__________'}</span>
                            </div>
                        `).join('')}
                    </div>
                </div>
            `).join('')}
            
            <div style="margin-top: 50px; font-style: italic; font-size: 12px; color: #777; text-align: center; border-top: 1px solid #eee; padding-top: 20px;">
                ${isRtl ? 'تم إنشاء هذا المستند بواسطة نظام مركز الإيمان الإسلامي' : 'This document was generated by the Iman Islamic Center system'}
            </div>
        </div>
    `;
};
